services:

    web:
        build:
            context: .
        image: ghcr.io/jandolejs/key:latest
        container_name: "${PROJECT_NAME}_web"
        restart: unless-stopped
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"

networks:
    web:
        name: www
        external: true
