version: "3.9"

services:

    web:
        build:
            context: .
        image: registry.digitalocean.com/mre/key
        container_name: "${PROJECT_NAME}_web"
        restart: always
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"

networks:
    web:
        name: www_key
        external: true
