version: "3.9"

services:

    web:
        build:
            context: .
        container_name: "${PROJECT_NAME}_php"
        restart: always
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web"
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls.certresolver=myresolver"

networks:
    web:
        name: key_jandolejs_cz
